### ISSUE TITLE
https://converter.swagger.io saves swagger files to their servers?

### ISSUE THREAD

**Issue by venkateshnamb** [swagger-api/swagger-converter#71]
"I have seen this connector that converts Swagger specifications to Open API. I have a question regarding the privacy of the Swagger file. In our organization, we process all the Swagger files, so I would like to know if they are going to save the Swagger files or the history of transactions on their servers. Or do these connectors run independently without relying on the SmartBear server or the application?

You can find the connector at https://converter.swagger.io/"

If am directly calling converter.swagger.io, is this storing swagger files what ever the document submitted?

Why I have this question is that, we have enterprise and private APIs which are to be used from the Corporate Network, so we are concerned about the data

https://learn.microsoft.com/en-us/connectors/swaggerconverterip/

**Comment by venkateshnamb** [comment]
@fehguy @frantuma @webron @HugoMario @ralphdoe 
Can you please comment on this, as I was waiting for the update to proceed in the tasks

**Comment by frantuma** [comment]
As mentioned by fehguy your best path is run your own instance as you like. Converter service hosted at converter.swagger.io does not store any data, but it's not meant to be used in high request rates / sensitive data environments
