### ISSUE TITLE
Paramters/in:body aren't converted to requestBody

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-converter#8]
Expecting...
```yaml
swagger: 2.0
info:
  title: Josh
  version: josh
paths:
  /josh:
    get:
      description: yolo
      parameters:
        - name: body
          in: body
          schema:
            type: object
      responses:
        '200':
          description: ok

```

To become...
```yaml
openapi: 3.0.0
info:
  title: Josh
  version: josh
paths:
  /josh:
    get:
      description: yolo
      requestBody:
        content:
          application/json: # default to the first consumes value? Or application/json
            schema:
              type: object
      responses:
        '200':
          description: ok
```

**Comment by OzBob** [comment]
Sorry, but why is requestBody used at all?

According to the [v3 spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md)

"The requestBody is only supported in HTTP methods where the HTTP 1.1 specification RFC7231 has explicitly defined semantics for request bodies. In other cases where the HTTP spec is vague, requestBody SHALL be ignored by consumers."

**Comment by hkosova** [comment]
@OzBob `requestBody` is OAS3 replacement for OAS2 `in: body` parameters.
